version: '3'


services:
  auth:
    build:
      dockerfile: ./docker/keycloak/Dockerfile
      context: .
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
